# Generated by Django 5.2.3 on 2025-07-23 17:03

import django.db.models.deletion
import django.utils.timezone
import welp_payflow.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='UDN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'UDN (Unidad de Negocio)',
                'verbose_name_plural': 'UDNs',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('authorized', 'Autorizado'), ('budgeted', 'Presupuestado'), ('rejected', 'Rechazado'), ('authorized_by_manager', 'Autorizado por Manager'), ('authorized_by_director', 'Autorizado por Director'), ('payment_authorized', 'Pago Autorizado'), ('processing_payment', 'Procesando Pago'), ('shipping', 'En Envío'), ('closed', 'Cerrado'), ('unknown', 'Desconocido')], default='open', max_length=30, verbose_name='Estado')),
                ('message_type', models.CharField(choices=[('status', 'Cambio de Estado'), ('feedback', 'Comentario/Feedback'), ('system', 'Sistema')], default='status', max_length=20, verbose_name='Tipo de Mensaje')),
                ('reported_on', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Reportada')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Cuerpo del Mensaje')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payflow_messages', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=welp_payflow.models.attachment_upload_path, verbose_name='Archivo')),
                ('attachment_type', models.CharField(choices=[('document', 'Documento'), ('image', 'Imagen'), ('other', 'Otro')], default='other', max_length=50, verbose_name='Tipo de Archivo')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='welp_payflow.message', verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
            },
        ),
        migrations.CreateModel(
            name='AccountingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('sector', models.ManyToManyField(related_name='accounting_categories', to='welp_payflow.sector', verbose_name='Sectores')),
            ],
            options={
                'verbose_name': 'Categoría Contable',
                'verbose_name_plural': 'Categorías Contables',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Solicitud')),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Estimado')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('accounting_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welp_payflow.accountingcategory', verbose_name='Categoría Contable')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welp_payflow.sector', verbose_name='Sector')),
                ('udn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welp_payflow.udn', verbose_name='UDN')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='welp_payflow.ticket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='sector',
            name='udn',
            field=models.ManyToManyField(related_name='payflow_sectors', to='welp_payflow.udn', verbose_name='UDNs'),
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', 'Director'), ('manager', 'Manager'), ('supervisor', 'Supervisor'), ('purchase_manager', 'Gestor de Compras'), ('technician', 'Técnico'), ('end_user', 'Usuario Final')], default='end_user', max_length=20, verbose_name='Rol Explícito')),
                ('can_open', models.BooleanField(default=False, verbose_name='Puede Abrir')),
                ('can_comment', models.BooleanField(default=False, verbose_name='Puede Comentar')),
                ('can_solve', models.BooleanField(default=False, verbose_name='Puede Gestionar Presupuestos')),
                ('can_authorize', models.BooleanField(default=False, verbose_name='Puede Autorizar')),
                ('can_process_payment', models.BooleanField(default=False, verbose_name='Puede Procesar Pagos')),
                ('can_close', models.BooleanField(default=False, verbose_name='Puede Cerrar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payflow_roles', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='welp_payflow.sector')),
                ('udn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='welp_payflow.udn')),
            ],
            options={
                'verbose_name': 'Rol y Permiso',
                'verbose_name_plural': 'Roles y Permisos',
                'unique_together': {('user', 'udn', 'sector')},
            },
        ),
    ]
