# Generated by Django 5.2.3 on 2025-08-05 13:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welp_payflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roles',
            unique_together={('user', 'udn', 'sector', 'role')},
        ),
    ]
