STATUS_MAX_LENGTH = 20

PAYFLOW_STATUSES = {
    'open': {
        'label': 'Abierto',
        'color': '#dc2626',
        'icon': '🔴',
        'description': 'Solicitud creada, esperando autorización inicial',
        'is_active': True,
        'is_final': False,
        'transitions': ['authorized', 'closed'],
    },
    'authorized': {
        'label': 'Autorizado',
        'color': '#a855f7',
        'icon': '🟣',
        'description': 'Solicitud autorizada, esperando presupuestos',
        'is_active': True,
        'is_final': False,
        'transitions': ['budgeted', 'closed'],
    },
    'budgeted': {
        'label': 'Presupuestado',
        'color': '#16a34a',
        'icon': '🟢',
        'description': 'Presupuestos adjuntados, esperando autorización de pago',
        'is_active': True,
        'is_final': False,
        'transitions': ['payment_authorized', 'rejected', 'closed'],
    },
    'rejected': {
        'label': 'Rechazado',
        'color': '#eab308',
        'icon': '🟡',
        'description': 'Presupuestos rechazados, requieren revisión',
        'is_active': True,
        'is_final': False,
        'transitions': ['budgeted', 'closed'],
    },
    'payment_authorized': {
        'label': 'Pago Autorizado',
        'color': '#f97316',
        'icon': '🔶',
        'description': 'Pago autorizado, esperando proceso de facturación',
        'is_active': True,
        'is_final': False,
        'transitions': ['processing_payment', 'closed'],
    },
    'processing_payment': {
        'label': 'Procesando Pago',
        'color': '#06b6d4',
        'icon': '💰',
        'description': 'Procesando pago/facturación',
        'is_active': True,
        'is_final': False,
        'transitions': ['shipping', 'closed'],
    },
    'shipping': {
        'label': 'En Envío',
        'color': '#8b5cf6',
        'icon': '📦',
        'description': 'En proceso de envío/entrega',
        'is_active': True,
        'is_final': False,
        'transitions': ['closed'],
    },
    'closed': {
        'label': 'Cerrado',
        'color': '#6b7280',
        'icon': '⚫',
        'description': 'Solicitud finalizada',
        'is_active': False,
        'is_final': True,
        'transitions': [],
    },
}

PAYFLOW_PERMISSIONS = [
    'can_open',
    'can_comment',
    'can_solve',
    'can_authorize',
    'can_process_payment',
    'can_close',
]

PAYFLOW_ROLE_PERMISSIONS = {
    'end_user': {
        'can_open': True,
        'can_comment': False,
        'can_solve': False,
        'can_authorize': False,
        'can_process_payment': False,
        'can_close': False,
    },
    'technician': {
        'can_open': True,
        'can_comment': True,
        'can_solve': True,
        'can_authorize': False,
        'can_process_payment': False,
        'can_close': False,
    },
    'supervisor': {
        'can_open': True,
        'can_comment': True,
        'can_solve': False,
        'can_authorize': True,
        'can_process_payment': False,
        'can_close': True,
    },
    'purchase_manager': {
        'can_open': False,
        'can_comment': True,
        'can_solve': True,
        'can_authorize': False,
        'can_process_payment': True,
        'can_close': False,
    },
    'manager': {
        'can_open': True,
        'can_comment': True,
        'can_solve': False,
        'can_authorize': True,
        'can_process_payment': True,
        'can_close': True,
    },
} 