import os
from django.conf import settings

STATUS_MAX_LENGTH = 30

PAYFLOW_STATUSES = {
    # Los estados se ordenan según el flujo de trabajo natural.
    'open': {
        'mermaid_node': 'A',
        'mermaid_style': 'fill:#fef2f2,stroke:#fecaca,stroke-width:2px,color:#dc2626,rx:20,ry:20',
        'label': 'Abierto',
        'color': '#dc2626',
        'color_name': 'red',
        'description': 'Solicitud creada, esperando autorización inicial',
        'is_active': True,
        'is_final': False,
        'transitions': ['authorized', 'closed'],
        'allowed_roles': [],
        'flow': {
            'current_action': 'Esperando autorización inicial',
            'next_action': 'Autorizar solicitud',
            'responsible_roles': ['supervisor', 'manager', 'director'],
            'is_waiting': True,
            'priority': 'high',
        },
        'action_verb': 'Solicitado',
        'show_comment_box': False,
        'show_attachments': False,
        'comment_required': False,
    },
    'authorized': {
        'mermaid_node': 'B',
        'mermaid_style': 'fill:#f3e8ff,stroke:#e9d5ff,stroke-width:2px,color:#a855f7,rx:20,ry:20',
        'label': 'Autorizado',
        'color': '#a855f7',
        'color_name': 'purple',
        'description': 'Solicitud autorizada, esperando presupuestos',
        'is_active': True,
        'is_final': False,
        'transitions': ['budgeted', 'closed'],
        'allowed_roles': ['supervisor', 'manager', 'director'],
        'flow': {
            'current_action': 'Esperando presupuestos',
            'next_action': 'Adjuntar presupuestos',
            'responsible_roles': ['technician', 'purchase_manager'],
            'is_waiting': True,
            'priority': 'medium',
        },
        'action_label': 'Autorizar',
        'action_verb': 'Solicitud autorizada',
        'color_class': 'text-purple-500',
        'confirmation_message': 'Confirmar autorización.',
        'button_text': 'Autorizar',
        'comment_placeholder': 'Comentario de autorización (opcional)',
        'comment_label': 'Comentario',
        'comment_required': False,
        'show_comment_box': False,
        'show_attachments': False,
    },
    'budgeted': {
        'mermaid_node': 'C',
        'mermaid_style': 'fill:#f0fdf4,stroke:#bbf7d0,stroke-width:2px,color:#10b981,rx:20,ry:20',
        'label': 'Presupuestado',
        'color': '#16a34a',
        'color_name': 'green',
        'description': 'Presupuestos adjuntados, esperando autorización de pago',
        'is_active': True,
        'is_final': False,
        'transitions': ['authorized_by_manager', 'authorized_by_director', 'rejected', 'closed'],
        'allowed_roles': ['purchase_manager', 'technician'],
        'flow': {
            'current_action': 'Esperando autorización de pago (doble firma)',
            'next_action': 'Autorización Manager y Director',
            'responsible_roles': ['manager', 'director'],
            'is_waiting': True,
            'priority': 'high',
        },
        'action_label': 'Presupuestar',
        'action_verb': 'Presupuestado',
        'color_class': 'text-green-600',
        'confirmation_message': '¿Confirmar presupuestos? Esto autoriza la preparación para el pago.',
        'confirmation_style': {'bg': 'bg-green-50', 'border': 'border-green-400', 'text': 'text-green-700'},
        'button_text': 'Enviar presupuesto',
        'comment_placeholder': 'Detalles del presupuesto adjuntado',
        'comment_label': 'Detalles del presupuesto',
        'comment_required': True,
        'show_comment_box': True,
        'show_attachments': True,
    },
    'rejected': {
        'mermaid_node': 'E',
        'mermaid_style': 'fill:#fef3c7,stroke:#fde68a,stroke-width:2px,color:#d97706,rx:20,ry:20',
        'label': 'Rechazado',
        'color': '#eab308',
        'color_name': 'yellow',
        'description': 'Presupuestos rechazados, requieren revisión',
        'is_active': True,
        'is_final': False,
        'transitions': ['budgeted', 'closed'],
        'allowed_roles': ['supervisor', 'manager', 'director'],
        'flow': {
            'current_action': 'Presupuestos rechazados',
            'next_action': 'Revisar y adjuntar nuevos presupuestos',
            'responsible_roles': ['technician', 'purchase_manager'],
            'is_waiting': True,
            'priority': 'high',
        },
        'action_label': 'Rechazar',
        'action_verb': 'Rechazado',
        'color_class': 'text-yellow-600',
        'confirmation_message': '¿Rechazar presupuestos? Se notificará al proveedor y se solicitará una nueva propuesta.',
        'confirmation_style': {'bg': 'bg-yellow-50', 'border': 'border-yellow-400', 'text': 'text-yellow-700'},
        'button_text': 'Rechazar',
        'comment_placeholder': 'Explique por qué se rechazan los presupuestos',
        'comment_label': 'Motivo del rechazo',
        'comment_required': True,
        'show_comment_box': True,
        'show_attachments': False,
    },
    'authorized_by_manager': {
        'mermaid_node': 'I',
        'mermaid_style': 'fill:#fff7ed,stroke:#fed7aa,stroke-width:2px,color:#f97316,rx:20,ry:20',
        'label': 'Autorizado por Manager',
        'color': '#f97316',
        'color_name': 'orange',
        'description': 'Primera firma completada, esperando segunda firma del Director',
        'allowed_roles': ['manager'],
        'action_label': 'Aprobar Pago',
        'action_verb': 'Autorizado por Manager',
        'color_class': 'text-orange-500',
        'confirmation_message': '¿Confirmar autorización como Manager? Si el Director ya autorizó, el pago se aprobará automáticamente.',
        'confirmation_style': {'bg': 'bg-orange-50', 'border': 'border-orange-400', 'text': 'text-orange-700'},
        'button_text': 'Autorizar Pago',
        'comment_placeholder': 'Comentario de autorización de Manager (opcional)',
        'comment_label': 'Comentario',
        'comment_required': False,
        'show_comment_box': False,
        'show_attachments': False,
    },
    'authorized_by_director': {
        'mermaid_node': 'J',
        'mermaid_style': 'fill:#fdf4ff,stroke:#e9d5ff,stroke-width:2px,color:#c084fc,rx:20,ry:20',
        'label': 'Autorizado por Director',
        'color': '#c084fc',
        'color_name': 'purple',
        'description': 'Segunda firma completada, pago autorizado automáticamente',
        'allowed_roles': ['director'],
        'action_label': 'Aprobar Pago',
        'action_verb': 'Autorizado por Director',
        'color_class': 'text-purple-500',
        'confirmation_message': '¿Confirmar autorización como Director? Si el Manager ya autorizó, el pago se aprobará automáticamente.',
        'confirmation_style': {'bg': 'bg-purple-50', 'border': 'border-purple-400', 'text': 'text-purple-700'},
        'button_text': 'Autorizar Pago',
        'comment_placeholder': 'Comentario de autorización de Director (opcional)',
        'comment_label': 'Comentario',
        'comment_required': False,
        'show_comment_box': False,
        'show_attachments': False,
    },
    'payment_authorized': {
        'mermaid_node': 'D',
        'mermaid_style': 'fill:#f3e8ff,stroke:#e9d5ff,stroke-width:2px,color:#a855f7,rx:20,ry:20',
        'label': 'Pago Autorizado',
        'color': '#a855f7',
        'color_name': 'purple',
        'description': 'Pago autorizado automáticamente tras doble firma, esperando proceso de facturación',
        'is_active': True,
        'is_final': False,
        'transitions': ['processing_payment'],
        'allowed_roles': ['system'],
        'flow': {
            'current_action': 'Esperando proceso de pago',
            'next_action': 'Procesar facturación',
            'responsible_roles': ['purchase_manager'],
            'is_waiting': True,
            'priority': 'medium',
        },
        'action_label': 'Autorizar Pago',
        'action_verb': 'Pago autorizado',
        'color_class': 'text-purple-500',
        'confirmation_message': '¿Autorizar pago? Esto inicia el proceso de facturación y desembolso.',
        'confirmation_style': {'bg': 'bg-purple-50', 'border': 'border-purple-400', 'text': 'text-purple-700'},
        'button_text': 'Autorizar pago',
        'comment_placeholder': 'Comentario de autorización de pago (opcional)',
        'comment_label': 'Comentario',
        'comment_required': False,
        'show_comment_box': False,
        'show_attachments': False,
    },
    'processing_payment': {
        'mermaid_node': 'G',
        'mermaid_style': 'fill:#cffafe,stroke:#a5f3fc,stroke-width:2px,color:#0891b2,rx:20,ry:20',
        'label': 'Procesando Pago',
        'color': '#06b6d4',
        'color_name': 'cyan',
        'description': 'Procesando pago/facturación',
        'is_active': True,
        'is_final': False,
        'transitions': ['shipping'],
        'allowed_roles': ['purchase_manager'],
        'flow': {
            'current_action': 'Procesando pago/facturación',
            'next_action': 'Confirmar envío',
            'responsible_roles': ['purchase_manager'],
            'is_waiting': False,
            'priority': 'low',
        },
        'action_label': 'Procesar Pago',
        'action_verb': 'Enviado a `Pagos y Proveedores`',
        'color_class': 'text-cyan-600',
        'confirmation_message': '¿Confirmar pago procesado? Esto marca el final del proceso de facturación.',
        'confirmation_style': {'bg': 'bg-cyan-50', 'border': 'border-cyan-400', 'text': 'text-cyan-700'},
        'button_text': 'Marcar como Procesando Pago',
        'comment_placeholder': 'Detalles del proceso de pago/facturación',
        'comment_label': 'Comentario',
        'comment_required': False,
        'show_comment_box': False,
        'show_attachments': False,
    },
    'shipping': {
        'mermaid_node': 'H',
        'mermaid_style': 'fill:#eef2ff,stroke:#c7d2fe,stroke-width:2px,color:#6366f1,rx:20,ry:20',
        'label': 'En Envío',
        'color': '#8b5cf6',
        'color_name': 'violet',
        'description': 'En proceso de envío/entrega',
        'is_active': True,
        'is_final': False,
        'transitions': ['closed'],
        'allowed_roles': ['purchase_manager', 'technician'],
        'flow': {
            'current_action': 'En proceso de envío/entrega',
            'next_action': 'Confirmar recepción',
            'responsible_roles': ['end_user', 'purchase_manager'],
            'is_waiting': False,
            'priority': 'low',
        },
        'action_label': 'Envío',
        'action_verb': 'Envío gestionado',
        'color_class': 'text-violet-600',
        'confirmation_message': '¿Confirmar envío? Se notificará al usuario final para la recepción.',
        'confirmation_style': {'bg': 'bg-violet-50', 'border': 'border-violet-400', 'text': 'text-violet-700'},
        'button_text': 'Marcar como En camino',
        'comment_placeholder': 'Detalles del envío/entrega (opcional)',
        'comment_label': 'Comentario',
        'comment_required': False,
        'show_comment_box': True,
        'show_attachments': True,
    },
    'closed': {
        'mermaid_node': 'F',
        'mermaid_style': 'fill:#f1f5f9,stroke:#e2e8f0,stroke-width:2px,color:#94a3b8,rx:20,ry:20',
        'label': 'Cerrado',
        'color': '#6b7280',
        'color_name': 'forest',
        'description': 'Solicitud finalizada',
        'is_active': False,
        'is_final': True,
        'transitions': [],
        'allowed_roles': [],
        'flow': {
            'current_action': 'Solicitud finalizada',
            'next_action': None,
            'responsible_roles': [],
            'is_waiting': False,
            'priority': None,
        },
        'action_label': 'Cerrar',
        'action_verb': 'Cerrado',
        'color_class': 'text-gray-500',
        'owner_message': 'Está cerrando su propio ticket.',
        'non_owner_message': 'Está cerrando un ticket creado por otro usuario.',
        'confirmation_style': {'bg': 'bg-yellow-50', 'border': 'border-yellow-400', 'text': 'text-yellow-700'},
        'confirmation_message': '¿Cerrar ticket? Esto finalizará la solicitud y no se podrán añadir más comentarios ni adjuntos.',
        'button_text': 'Confirmar Cierre',
        'comment_placeholder': 'Explique el motivo del cierre',
        'comment_label': 'Comentario',
        'comment_required': True,
        'show_comment_box': True,
        'show_attachments': False,
    },

    # Tipos especiales para acciones de UI que no son estados reales de ticket.
    'comment': {
        'action_label': 'Comentar',
        'action_verb': 'Comentado',
        'color_class': 'text-gray-400',
        'button_text': 'Comentar',
        'comment_required': True,
        'show_comment_box': True,
        'show_attachments': True,
    },

    # Estado de fallback
    'unknown': {
        'label': 'Desconocido',
        'color': '#d1d5db',
        'color_name': 'gray',
        'description': 'Estado desconocido',
        'is_active': False,
        'is_final': False,
        'transitions': [],
        'allowed_roles': [],
        'flow': {},
        'show_comment_box': False,
        'show_attachments': False,
        'comment_required': False,
    },
}

PAYFLOW_PERMISSIONS = ['can_open', 'can_comment', 'can_solve', 'can_authorize', 'can_process_payment', 'can_close']

PAYFLOW_ROLE_PERMISSIONS = {
    'end_user': {
        'can_open': True,
        'can_comment': False,
        'can_solve': False,
        'can_authorize': False,
        'can_process_payment': False,
        'can_close': False,
        'can_view_others_tickets': False,
    },
    'technician': {
        'can_open': True,
        'can_comment': True,
        'can_solve': True,
        'can_authorize': False,
        'can_process_payment': False,
        'can_close': False,
        'can_view_others_tickets': False,
    },
    'supervisor': {
        'can_open': True,
        'can_comment': True,
        'can_solve': False,
        'can_authorize': True,
        'can_process_payment': False,
        'can_close': True,
        'can_view_others_tickets': True,
    },
    'purchase_manager': {
        'can_open': False,
        'can_comment': True,
        'can_solve': True,
        'can_authorize': False,
        'can_process_payment': True,
        'can_close': False,
        'can_view_others_tickets': True,
    },
    'manager': {
        'can_open': True,
        'can_comment': True,
        'can_solve': False,
        'can_authorize': True,
        'can_process_payment': True,
        'can_close': True,
        'can_view_others_tickets': True,
    },
    'director': {
        'can_open': True,
        'can_comment': True,
        'can_solve': False,
        'can_authorize': True,
        'can_process_payment': True,
        'can_close': True,
        'can_view_others_tickets': True,
    },
}

MAX_FILE_SIZE = 52428800

API_BASE_URL = '/api/payflow/'
SELECT_OPTIONS_ENDPOINT = 'select-options'

FORM_TIMEOUT_SECONDS = 300 
MAX_UPLOAD_FILES = 10 

TREEMAP_MIN_ITEMS = 3 
TREEMAP_MAX_ITEMS = 50 

FA_ICONS = {
    "open": "fa-solid fa-file-signature",
    "feedback": "fa-solid fa-comment-dots",
    "authorized": "fa-solid fa-check",
    'budgeted': 'fa-solid fa-file-invoice-dollar',
    'rejected': 'fa-solid fa-ban',
    'authorized_by_manager': 'fa-solid fa-user-check',
    'authorized_by_director': 'fa-solid fa-user-check',
    'payment_authorized': 'fa-solid fa-check',
    'processing_payment': 'fa-solid fa-cash-register',
    'shipping': 'fa-solid fa-truck-fast',
    'close': 'fa-solid fa-lock',
    'view': 'fa-solid fa-eye',
} 