# Generated by Django 5.2.3 on 2025-07-23 17:03

import django.db.models.deletion
import welp_desk.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría de Incidencia',
                'verbose_name_plural': 'Categorías de Incidencias',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='UDN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'UDN (Unidad de Negocio)',
                'verbose_name_plural': 'UDNs',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre a Mostrar')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('issue_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='welp_desk.issuecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('comment', 'Comentado'), ('in_progress', 'En Progreso'), ('solved', 'Solucionado'), ('authorized', 'Autorizado'), ('rejected', 'Rechazado'), ('closed', 'Cerrado')], default='open', max_length=20, verbose_name='Estado')),
                ('reported_on', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Reportada')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Cuerpo del Mensaje')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welp_messages', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=welp_desk.models.attachment_upload_path, verbose_name='Archivo')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='welp_desk.message', verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
            },
        ),
        migrations.AddField(
            model_name='issuecategory',
            name='sector',
            field=models.ManyToManyField(related_name='issue_categories', to='welp_desk.sector', verbose_name='Sectores'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welp_desk.issue', verbose_name='Incidencia')),
                ('issue_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welp_desk.issuecategory', verbose_name='Categoría')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welp_desk.sector', verbose_name='Sector')),
                ('udn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welp_desk.udn', verbose_name='UDN')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='welp_desk.ticket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='sector',
            name='udn',
            field=models.ManyToManyField(related_name='sectors', to='welp_desk.udn', verbose_name='UDNs'),
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=False, verbose_name='Puede Leer')),
                ('can_comment', models.BooleanField(default=False, verbose_name='Puede Comentar')),
                ('can_solve', models.BooleanField(default=False, verbose_name='Puede Solucionar')),
                ('can_authorize', models.BooleanField(default=False, verbose_name='Puede Autorizar')),
                ('can_open', models.BooleanField(default=False, verbose_name='Puede Abrir')),
                ('can_close', models.BooleanField(default=False, verbose_name='Puede Cerrar')),
                ('issue_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='welp_desk.issuecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welp_roles', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='welp_desk.sector')),
                ('udn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='welp_desk.udn')),
            ],
            options={
                'verbose_name': 'Rol y Permiso',
                'verbose_name_plural': 'Roles y Permisos',
                'unique_together': {('user', 'udn', 'sector', 'issue_category')},
            },
        ),
    ]
