STATUS_MAX_LENGTH = 20

DESK_STATUSES = {
    'open': {
        'label': 'Abierto',
        'color': '#dc2626',
        'icon': '🔴',
        'description': 'Ticket abierto, esperando asignación',
        'is_active': True,
        'is_final': False,
        'transitions': ['comment', 'in_progress', 'solved', 'closed'],
        'requires_comment': False,
    },
    'comment': {
        'label': 'Comentado',
        'color': '#2563eb',
        'icon': '💬',
        'description': 'Ticket con comentarios del usuario o técnico',
        'is_active': True,
        'is_final': False,
        'transitions': ['in_progress', 'solved', 'closed'],
        'requires_comment': False,
    },
    'in_progress': {
        'label': 'En Progreso',
        'color': '#f59e0b',
        'icon': '🟡',
        'description': 'Ticket en progreso, siendo trabajado',
        'is_active': True,
        'is_final': False,
        'transitions': ['comment', 'solved', 'authorized', 'closed'],
        'requires_comment': True,
    },
    'solved': {
        'label': 'Solucionado',
        'color': '#16a34a',
        'icon': '🟢',
        'description': 'Ticket solucionado, esperando autorización',
        'is_active': True,
        'is_final': False,
        'transitions': ['authorized', 'rejected', 'closed'],
        'requires_comment': True,
    },
    'authorized': {
        'label': 'Autorizado',
        'color': '#8b5cf6',
        'icon': '🟣',
        'description': 'Solución autorizada, ticket cerrado automáticamente',
        'is_active': False,
        'is_final': True,
        'transitions': [],
        'requires_comment': False,
    },
    'rejected': {
        'label': 'Rechazado',
        'color': '#e11d48',
        'icon': '🔴',
        'description': 'Solución rechazada, requiere revisión',
        'is_active': True,
        'is_final': False,
        'transitions': ['comment', 'in_progress', 'closed'],
        'requires_comment': True,
    },
    'closed': {
        'label': 'Cerrado',
        'color': '#6b7280',
        'icon': '⚫',
        'description': 'Ticket cerrado manualmente',
        'is_active': False,
        'is_final': True,
        'transitions': [],
        'requires_comment': False,
    },
}

DESK_PERMISSIONS = [
    'can_read',
    'can_comment',
    'can_solve',
    'can_authorize',
    'can_open',
    'can_close',
]

DESK_ROLE_PERMISSIONS = {
    'end_user': {
        'can_read': True,
        'can_comment': False,
        'can_solve': False,
        'can_authorize': False,
        'can_open': True,
        'can_close': False,
    },
    'technician': {
        'can_read': True,
        'can_comment': True,
        'can_solve': True,
        'can_authorize': False,
        'can_open': True,
        'can_close': False,
    },
    'supervisor': {
        'can_read': True,
        'can_comment': True,
        'can_solve': False,
        'can_authorize': True,
        'can_open': True,
        'can_close': True,
    },
    'admin': {
        'can_read': True,
        'can_comment': True,
        'can_solve': True,
        'can_authorize': True,
        'can_open': True,
        'can_close': True,
    },
} 